//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Proto/BossStructure.proto
namespace ProtoData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RaidBossData")]
  public partial class RaidBossData : global::ProtoBuf.IExtensible
  {
    public RaidBossData() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RaidEnterData")]
  public partial class RaidEnterData : global::ProtoBuf.IExtensible
  {
    public RaidEnterData() {}
    
    private ProtoData.RaidBossData _raidBossData;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"raidBossData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoData.RaidBossData raidBossData
    {
      get { return _raidBossData; }
      set { _raidBossData = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoData.RaidEnterData.CharacterData> _characterDataList = new global::System.Collections.Generic.List<ProtoData.RaidEnterData.CharacterData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"characterDataList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoData.RaidEnterData.CharacterData> characterDataList
    {
      get { return _characterDataList; }
    }
  
    private int _totalScore;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"totalScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalScore
    {
      get { return _totalScore; }
      set { _totalScore = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterData")]
  public partial class CharacterData : global::ProtoBuf.IExtensible
  {
    public CharacterData() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _amount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}