//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Proto/BuildingStructure.proto
namespace ProtoData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildingClickData")]
  public partial class BuildingClickData : global::ProtoBuf.IExtensible
  {
    public BuildingClickData() {}
    
    private int _clickAction;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clickAction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int clickAction
    {
      get { return _clickAction; }
      set { _clickAction = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}