//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Proto/UserStructure.proto
namespace ProtoData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserData")]
  public partial class UserData : global::ProtoBuf.IExtensible
  {
    public UserData() {}
    
    private string _id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _nickname = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private int _race = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"race", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int race
    {
      get { return _race; }
      set { _race = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceData")]
  public partial class ResourceData : global::ProtoBuf.IExtensible
  {
    public ResourceData() {}
    
    private string _gold = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private string _cash = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cash", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cash
    {
      get { return _cash; }
      set { _cash = value; }
    }
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _tier = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"tier", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tier
    {
      get { return _tier; }
      set { _tier = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DBLoadData")]
  public partial class DBLoadData : global::ProtoBuf.IExtensible
  {
    public DBLoadData() {}
    
    private ProtoData.ResourceData _resourceData;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resourceData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoData.ResourceData resourceData
    {
      get { return _resourceData; }
      set { _resourceData = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoData.DBLoadData.BuildingData> _buildingDataList = new global::System.Collections.Generic.List<ProtoData.DBLoadData.BuildingData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"buildingDataList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoData.DBLoadData.BuildingData> buildingDataList
    {
      get { return _buildingDataList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildingData")]
  public partial class BuildingData : global::ProtoBuf.IExtensible
  {
    public BuildingData() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _LV = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"LV", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int LV
    {
      get { return _LV; }
      set { _LV = value; }
    }
    private long _tick = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private int _amount = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatData")]
  public partial class ChatData : global::ProtoBuf.IExtensible
  {
    public ChatData() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private string _nickname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RaidRankingData")]
  public partial class RaidRankingData : global::ProtoBuf.IExtensible
  {
    public RaidRankingData() {}
    
    private ProtoData.RaidRankingData.RankingData _myRankingData;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"myRankingData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoData.RaidRankingData.RankingData myRankingData
    {
      get { return _myRankingData; }
      set { _myRankingData = value; }
    }
    private ProtoData.RaidRankingData.RankingData _lastHitRankingData = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lastHitRankingData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoData.RaidRankingData.RankingData lastHitRankingData
    {
      get { return _lastHitRankingData; }
      set { _lastHitRankingData = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoData.RaidRankingData.RankingData> _rankingDataList = new global::System.Collections.Generic.List<ProtoData.RaidRankingData.RankingData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rankingDataList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoData.RaidRankingData.RankingData> rankingDataList
    {
      get { return _rankingDataList; }
    }
  
    private long _tick;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankingData")]
  public partial class RankingData : global::ProtoBuf.IExtensible
  {
    public RankingData() {}
    
    private string _nickname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private int _index;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _tier;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"tier", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tier
    {
      get { return _tier; }
      set { _tier = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _ranking;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ranking
    {
      get { return _ranking; }
      set { _ranking = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RaidRankingScoreData")]
  public partial class RaidRankingScoreData : global::ProtoBuf.IExtensible
  {
    public RaidRankingScoreData() {}
    
    private int _score;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}