//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Proto/UserStructure.proto
namespace ProtoData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserData")]
  public partial class UserData : global::ProtoBuf.IExtensible
  {
    public UserData() {}
    
    private string _id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _nickname = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private int _race = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"race", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int race
    {
      get { return _race; }
      set { _race = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceData")]
  public partial class ResourceData : global::ProtoBuf.IExtensible
  {
    public ResourceData() {}
    
    private string _gold = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private string _cash = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cash", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cash
    {
      get { return _cash; }
      set { _cash = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DBLoadData")]
  public partial class DBLoadData : global::ProtoBuf.IExtensible
  {
    public DBLoadData() {}
    
    private ProtoData.ResourceData _resourceData;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resourceData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoData.ResourceData resourceData
    {
      get { return _resourceData; }
      set { _resourceData = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoData.DBLoadData.BuildingData> _buildingDataList = new global::System.Collections.Generic.List<ProtoData.DBLoadData.BuildingData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"buildingDataList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoData.DBLoadData.BuildingData> buildingDataList
    {
      get { return _buildingDataList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildingData")]
  public partial class BuildingData : global::ProtoBuf.IExtensible
  {
    public BuildingData() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _LV = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"LV", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int LV
    {
      get { return _LV; }
      set { _LV = value; }
    }
    private long _tick = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tick
    {
      get { return _tick; }
      set { _tick = value; }
    }
    private int _amount = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}